export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const FETCH_FAVORITES_REQUEST = 'FETCH_FAVORITES_REQUEST';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAILURE = 'FETCH_FAVORITES_FAILURE';

export const ADD_FAVORITES_REQUEST = 'ADD_FAVORITES_REQUEST';
export const ADD_FAVORITES_SUCCESS = 'ADD_FAVORITES_SUCCESS';
export const ADD_FAVORITES_FAILURE = 'ADD_FAVORITES_FAILURE';

export const REMOVE_FAVORITES_REQUEST = 'REMOVE_FAVORITES_REQUEST';
export const REMOVE_FAVORITES_SUCCESS = 'REMOVE_FAVORITES_SUCCESS';
export const REMOVE_FAVORITES_FAILURE = 'REMOVE_FAVORITES_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const AUTH_STATUS = 'AUTH_STATUS';

export const ADD_FAV_REQUEST = 'ADD_FAV_REQUEST';
export const ADD_FAV_SUCCESS = 'ADD_FAV_SUCCESS';
export const ADD_FAV_FAILURE = 'ADD_FAV_FAILURE';

export const FETCH_FAV_REQUEST = 'FETCH_FAV_REQUEST';
export const FETCH_FAV_SUCCESS = 'FETCH_FAV_SUCCESS';
export const FETCH_FAV_FAILURE = 'FETCH_FAV_FAILURE';

export const REMOVE_FAV_REQUEST = 'REMOVE_FAV_REQUEST';
export const REMOVE_FAV_SUCCESS = 'REMOVE_FAV_SUCCESS';
export const REMOVE_FAV_FAILURE = 'REMOVE_FAV_FAILURE';

export const FAVORITES = 'FAVORITES';
